{"status": "REJECTED", "transaction_failure_reason": {"code": "TRANSACTION_FAILED", "error_message": "Error at pc=0:15:\nGot an exception while executing a hint.\nCairo traceback (most recent call last):\nUnknown location (pc=0:527)\nUnknown location (pc=0:515)\nUnknown location (pc=0:471)\nUnknown location (pc=0:105)\n\nError in the called contract (0x1fc60ff13e22ce69694ca292d3c256028205aec5b7742013eb1cc2cd7e0a26e):\nError at pc=0:816:\nAn ASSERT_EQ instruction failed: 0 != 1.\nCairo traceback (most recent call last):\nUnknown location (pc=0:1005)\nUnknown location (pc=0:931)"}, "transaction": {"transaction_hash": "0x533d327336f28b973c7f06f7abf15af7f8fd5a1bd4e1991397ae59e49a59885", "version": "0x0", "max_fee": "0x0", "signature": [], "entry_point_selector": "0x1aa84a767d5094ca8e64ada611789450e62e960d5f117615eda66fe1a26559", "calldata": [], "contract_address": "0x3365bd7f53fb497dd5f1a86a5d8a4b422900cd2882e85227f897284ee7a51ac", "type": "INVOKE_FUNCTION"}}